// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netproject2.Data;

#nullable disable

namespace netproject2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("netproject2.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<decimal>("AssignmentResult")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("AssignmentValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentID");

                    b.HasIndex("SubjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentID = 1,
                            AssignmentResult = 0.0m,
                            AssignmentType = "Homework",
                            AssignmentValue = 10.0m,
                            Description = "indiviudal report",
                            DueDate = new DateTime(2024, 11, 2, 23, 15, 5, 533, DateTimeKind.Local).AddTicks(1326),
                            SubjectId = 1,
                            Title = "Assignment1: report",
                            UserId = 1
                        },
                        new
                        {
                            AssignmentID = 2,
                            AssignmentResult = 0.0m,
                            AssignmentType = "Lab Report",
                            AssignmentValue = 20.0m,
                            Description = "Write a report on the mechanics lab",
                            DueDate = new DateTime(2024, 11, 5, 23, 15, 5, 533, DateTimeKind.Local).AddTicks(1419),
                            SubjectId = 2,
                            Title = "Assignment2: group report",
                            UserId = 1
                        },
                        new
                        {
                            AssignmentID = 3,
                            AssignmentResult = 0.0m,
                            AssignmentType = "Research Paper",
                            AssignmentValue = 30.0m,
                            Description = "Research on organic compounds and submit a paper",
                            DueDate = new DateTime(2024, 11, 9, 23, 15, 5, 533, DateTimeKind.Local).AddTicks(1424),
                            SubjectId = 3,
                            Title = "Organic Chemistry Research",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("netproject2.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Description = "Algebra and Geometry",
                            SubjectName = "Mathematics",
                            UserId = 1
                        },
                        new
                        {
                            SubjectId = 2,
                            Description = "Mechanics and Optics",
                            SubjectName = "Physics",
                            UserId = 1
                        },
                        new
                        {
                            SubjectId = 3,
                            Description = "Organic and Inorganic",
                            SubjectName = "Chemistry",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("netproject2.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            Password = "password123"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "jane.smith@example.com",
                            FullName = "Jane Smith",
                            Password = "password456"
                        });
                });

            modelBuilder.Entity("netproject2.Models.Assignment", b =>
                {
                    b.HasOne("netproject2.Models.Subject", "Subject")
                        .WithMany("Assignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("netproject2.Models.Subject", b =>
                {
                    b.HasOne("netproject2.Models.User", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("netproject2.Models.Subject", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("netproject2.Models.User", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
